enum TEXTNODES {
  SHOW_MORE = 'Show more',
  FILTERS = 'Filters',
  SORT_BY = 'Sort by',
  RATING = 'Rating',
  YEAR = 'Year',
  FULL_OR_SHOT_MOVIE_NAME = 'Full or short movie name',
  GENRES = 'Genres',
  YEARS = 'Years',
  COUNTRY = 'Country',
  CLEAR_FILTERS = 'Clear filter',
  SHOW_RESULTS = 'Show results',
  RIGHTS = 'All Rights Reserved',
  RELEASED = 'Released',
  BOX_OFFICE = 'BoxOffice',
  PRODUCTION = 'Production',
  ACTORS = 'Actors',
  RECOMMENDATIONS = 'Recommendations',
  NAME = 'Name',
  EMAIL = 'Email',
  PASSWORD = 'Password',
  CONFIRM_PASSWORD = 'Confirm password',
  FORGOT_PASSWORD = 'Forgot password?',
  RESET_PASSWORD = 'Reset Password',
  NEW_PASSWORD = 'New password',
  PROFILE = 'Profile',
  COLOR_MODE = 'Color mode',
  DARK = 'Dark',
  USE_DARK_THEME = 'Use dark theme',
  CANCEL = 'Cancel',
  SAVE = 'Save',
  HOME = 'Home',
  TRENDS = 'Trends',
  FAVORITES = 'Favorites',
  SETTINGS = 'Settings',
  SIGN_UP = 'Sign Up',
  HAVE_ACCOUNT = 'Already have an account?',
  SIGN_IN = 'Sign In',
  NO_ACCOUNT = 'Don’t have an account?',
  LOG_OUT = 'Log out',
}

export default TEXTNODES;
